name: Docker Image CI for GHCR
on:
  push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - uses: docker/build-push-action@v3
      - name: Build and push Docker image
        run: |
          docker login --username munagalasandeep99 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/munagalasandeep99/wexa_ai_assignment:latest
          docker push ghcr.io/munagalasandeep99/wexa_ai_assignment:latest